import type { PlanningPolicy } from "./graph.ts";
import type { PlannerProposal } from "./planner.ts";

export const policy: PlanningPolicy = {
  allowedRepositories: ["/tmp/configured-repository"],
  supportedAgents: {
    analyze: ["coordinator"],
    modify: ["developer-1"],
    validate: ["test-executor"],
    report: ["coordinator"],
  },
  allowedCommands: ["pnpm test target"],
  requiredDenyScopes: [".env*", ".git/**"],
  limits: {
    maxCommandsPerPlan: 2,
    maxMinutesPerNode: 30,
    maxAttemptsPerNode: 3,
    maxTokensPerNode: 20_000,
    maxTokensPerPlan: 50_000,
  },
};

export function validProposal(): PlannerProposal {
  const budget = { maxMinutes: 10, maxAttempts: 2, maxTokens: 10_000 };
  return {
    version: 1,
    summary: "顺序完成分析、修改、验证和汇报",
    nodes: [
      {
        id: "analyze-goal",
        type: "analyze",
        agentId: "coordinator",
        dependsOn: [],
        objective: "形成受约束的修改分析",
        inputEvidence: ["snapshot:goal", "snapshot:acceptance"],
        instructions: "分析目标和证据",
        readScope: ["**/*"],
        writeScope: [],
        denyScope: [".env*", ".git/**"],
        commands: [],
        expectedArtifacts: ["analysis.json"],
        completionDefinition: "输出可执行范围和风险",
        risk: "low",
        budget,
      },
      {
        id: "modify-code",
        type: "modify",
        agentId: "developer-1",
        dependsOn: ["analyze-goal"],
        objective: "生成隔离候选修改",
        inputEvidence: ["node:analyze-goal"],
        instructions: "在隔离 worktree 修改",
        readScope: ["src/**", "server/**"],
        writeScope: ["src/**", "server/**"],
        denyScope: [".env*", ".git/**"],
        commands: [],
        expectedArtifacts: ["candidate-commit"],
        completionDefinition: "候选 commit 位于声明范围内",
        risk: "medium",
        budget,
      },
      {
        id: "validate-candidate",
        type: "validate",
        agentId: "test-executor",
        dependsOn: ["modify-code"],
        objective: "确定性验证候选",
        inputEvidence: ["node:modify-code"],
        instructions: "执行确定性目标测试",
        readScope: ["**/*"],
        writeScope: [],
        denyScope: [".env*", ".git/**"],
        commands: ["pnpm test target"],
        expectedArtifacts: ["test-evidence.json"],
        completionDefinition: "记录测试命令、退出码和受控结论",
        risk: "low",
        budget,
      },
      {
        id: "report-evidence",
        type: "report",
        agentId: "coordinator",
        dependsOn: ["validate-candidate"],
        objective: "汇报候选和证据",
        inputEvidence: ["node:validate-candidate"],
        instructions: "汇报受控证据状态",
        readScope: [],
        writeScope: [],
        denyScope: [".env*", ".git/**"],
        commands: [],
        expectedArtifacts: ["status-card"],
        completionDefinition: "准确区分候选、目标测试和完整门禁",
        risk: "low",
        budget,
      },
    ],
  };
}
