/** Bake matching contour samples from the shipped catalog; no geometry parsing at runtime. */
import { writeFileSync } from "node:fs";
import { MASCOT_BODIES, MASCOT_BODY_IDS } from "../shared/mascot-bodies.ts";
import { applyFit, flatten } from "./mascot-bodies/geometry.ts";

const COUNT = 96;

const entries = MASCOT_BODY_IDS.map(id => {
  const body = MASCOT_BODIES[id];
  const path = body.clip.match(/ d="([^"]+)"/)?.[1];
  const fit = body.fit.match(/^translate\(([-\d.]+) ([-\d.]+)\) scale\(([-\d.]+)\)$/);
  if (!path || !fit) throw new Error(`Unsupported catalog outline: ${id}`);
  const lines = applyFit(flatten(path), { tx: Number(fit[1]), ty: Number(fit[2]), scale: Number(fit[3]) });
  if (lines.length !== 1) throw new Error(`Expected one closed contour: ${id}`);
  const ring = lines[0];
  if (Math.hypot(ring[0][0] - ring.at(-1)![0], ring[0][1] - ring.at(-1)![1]) > 1e-6) {
    throw new Error(`Open contour: ${id}`);
  }
  ring.pop();
  const area = ring.reduce((sum, p, i) => {
    const q = ring[(i + 1) % ring.length];
    return sum + p[0] * q[1] - q[0] * p[1];
  }, 0);
  if (area < 0) ring.reverse();
  // Start at the top, choosing the central point when a flat edge has a tie.
  const midX = (Math.min(...ring.map(p => p[0])) + Math.max(...ring.map(p => p[0]))) / 2;
  const minY = Math.min(...ring.map(p => p[1]));
  for (let i = 0; i < ring.length; i++) {
    const p = ring[i];
    const q = ring[(i + 1) % ring.length];
    if (Math.abs(p[1] - minY) < 1e-6 && Math.abs(q[1] - minY) < 1e-6 &&
        midX > Math.min(p[0], q[0]) && midX < Math.max(p[0], q[0])) {
      ring.splice(i + 1, 0, [midX, minY]);
      break;
    }
  }
  let start = 0;
  ring.forEach((p, i) => {
    if (p[1] < ring[start][1] - 1e-6 ||
        (Math.abs(p[1] - ring[start][1]) < 1e-6 && Math.abs(p[0] - midX) < Math.abs(ring[start][0] - midX))) start = i;
  });
  const ordered = [...ring.slice(start), ...ring.slice(0, start), ring[start]];
  const distances = [0];
  for (let i = 1; i < ordered.length; i++) {
    distances.push(distances[i - 1] + Math.hypot(ordered[i][0] - ordered[i - 1][0], ordered[i][1] - ordered[i - 1][1]));
  }
  const length = distances.at(-1)!;
  let edge = 0;
  const points: number[] = [];
  for (let i = 0; i < COUNT; i++) {
    const distance = length * i / COUNT;
    while (distances[edge + 1] <= distance) edge++;
    const t = (distance - distances[edge]) / (distances[edge + 1] - distances[edge]);
    for (let axis = 0; axis < 2; axis++) {
      points.push(Number((ordered[edge][axis] + (ordered[edge + 1][axis] - ordered[edge][axis]) * t).toFixed(3)));
    }
  }
  if (!points.every(Number.isFinite)) throw new Error(`Non-finite samples: ${id}`);
  return `  ${id}: [${points.join(", ")}],`;
});

const output = `/**
 * GENERATED by node --experimental-strip-types scripts/gen-mascot-motion.ts.
 * Regenerate after gen:bodies. Closed clockwise contours, starting at the top,
 * sampled at equal arc lengths in fitted face space. Used only while morphing.
 */
import type { MascotBodyId } from "./mascot-bodies";

export const MASCOT_MOTION_POINT_COUNT = ${COUNT};
export const MASCOT_MOTION_POINTS: Record<MascotBodyId, readonly number[]> = {
${entries.join("\n")}
};
`;

if (process.argv.includes("--check")) {
  const { readFileSync } = await import("node:fs");
  if (readFileSync(new URL("../shared/mascot-motion-points.ts", import.meta.url), "utf8") !== output) {
    throw new Error("Mascot motion samples are stale; run scripts/gen-mascot-motion.ts");
  }
} else {
  writeFileSync(new URL("../shared/mascot-motion-points.ts", import.meta.url), output);
}
